<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>00746cd7-ddba-4f0d-9381-49774cd901c5</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigateToEnterKey</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[8]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/project/1867424/tests/test-cases/10751034') and equals(@text,'TC-10751034 Enter Key Functionality on Login')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Navigate to Enter Key\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/project/1867424/tests/test-cases/10751034</value>
        <webElementGuid>7c037451-43f3-4a9f-9251-0b0ebca51390</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TC-10751034 Enter Key Functionality on Login</value>
        <webElementGuid>7c037451-43f3-4a9f-9251-0b0ebca51390</webElementGuid>
    </webElementProperties>
</WebElementEntity>