<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6d57d8a7-dc0a-4f3b-8b47-26c1f0fc3fba</elementGuidId>
    <imagePath></imagePath>
    <name>list_testCasesTestSuitesJourney</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/ul[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"Test CasesTest SuitesJourney\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>